In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
# specify the url to scrape
url_2020 = 'https://web.archive.org/web/20200630235307/https://www.house.gov/representatives'
url_2021 = 'https://web.archive.org/web/20210701010009/https://www.house.gov/representatives'
url_2022 = 'https://web.archive.org/web/20220701092720/https://www.house.gov/representatives'

In [3]:
# make a request to the website and store the HTML content in a variable
response_2020 = requests.get(url_2020)
html_content_2020 = response_2020.content

In [4]:
response_2021 = requests.get(url_2021)
html_content_2021 = response_2021.content

In [5]:
response_2022 = requests.get(url_2022)
html_content_2022 = response_2022.content

In [6]:
# parse the HTML content using BeautifulSoup
soup_2020 = BeautifulSoup(html_content_2020, 'html.parser')

soup_2021 = BeautifulSoup(html_content_2021, 'html.parser')

soup_2022 = BeautifulSoup(html_content_2022, 'html.parser')

In [7]:
# fix anomily in 2022 data which has "|" as divider. REMOVE IT
soup_2022_str = soup_2022.prettify().replace("|", "")
soup_2022 = BeautifulSoup(soup_2022_str, 'html.parser')

In [8]:
# find all tables on the soup object
tables_2020 = soup_2020.find_all('table')

tables_2021 = soup_2021.find_all('table')

tables_2022 = soup_2022.find_all('table')

In [9]:
# create an empty list to store the dataframes
dataframes_2020 = []

dataframes_2021 = []

dataframes_2022 = []

In [10]:
# loop through all tables and convert them to dataframes
for table in tables_2020:
    df = pd.read_html(str(table))[0]
    dataframes_2020.append(df)

for table in tables_2021:
    df = pd.read_html(str(table))[0]
    dataframes_2021.append(df)
    
for table in tables_2022:
    df = pd.read_html(str(table))[0]
    dataframes_2022.append(df)

In [11]:
# concatenate the list of dataframes into one, along the rows (axis=0)
committee_2020 = pd.concat(dataframes_2020, axis=0, ignore_index=True)

committee_2021 = pd.concat(dataframes_2021, axis=0, ignore_index=True)

committee_2022 = pd.concat(dataframes_2022, axis=0, ignore_index=True)

In [12]:
committee_2020

,District,Name,Party,Office Room,Phone,Committee Assignment
0,1st,"Byrne, Bradley",R,119 CHOB,(202) 225-4931,Armed ServicesEducation and Labor
1,2nd,"Roby, Martha",R,504 CHOB,(202) 225-2901,AppropriationsJudiciary
2,3rd,"Rogers, Mike",R,2184 RHOB,(202) 225-3261,Armed ServicesHomeland Security
3,4th,"Aderholt, Robert",R,1203 LHOB,(202) 225-4876,Appropriations
4,5th,"Brooks, Mo",R,2246 RHOB,(202) 225-4801,"Armed ServicesScience, Space, and Technology"
...,...,...,...,...,...,...
877,Texas 6th,"Wright, Ron",R,428 CHOB,(202) 225-2002,Education and LaborForeign Affairs
878,Kentucky 3rd,"Yarmuth, John A.",D,402 CHOB,(202) 225-5401,Budget
879,Florida 3rd,"Yoho, Ted",R,1730 LHOB,(202) 225-5744,AgricultureForeign Affairs
880,Alaska At Large,"Young, Don",R,2314 RHOB,(202) 225-5765,Natural ResourcesTransportation and Infrastruc...
881,New York 1st,"Zeldin, Lee",R,2441 RHOB,(202) 225-3826,Financial ServicesForeign Affairs

In [13]:
committee_2021

,District,Name,Party,Office Room,Phone,Committee Assignment
0,1st,"Carl, Jerry L.",R,1330 LHOB,(202) 225-4931,Armed ServicesNatural Resources
1,2nd,"Moore, Barry",R,1504 LHOB,(202) 225-2901,AgricultureVeterans' Affairs
2,3rd,"Rogers, Mike",R,2469 RHOB,(202) 225-3261,Armed Services
3,4th,"Aderholt, Robert",R,266 CHOB,(202) 225-4876,Appropriations
4,5th,"Brooks, Mo",R,2185 RHOB,(202) 225-4801,"Armed ServicesScience, Space, and Technology"
...,...,...,...,...,...,...
877,Arkansas 3rd,"Womack, Steve",R,2412 RHOB,(202) 225-4301,Appropriations
878,Texas 6th,"Wright, Ron- Vacancy",R,1725 LHOB,(202) 225-2002,NaN
879,Kentucky 3rd,"Yarmuth, John A.",D,402 CHOB,(202) 225-5401,BudgetEducation and Labor
880,Alaska At Large,"Young, Don",R,2314 RHOB,(202) 225-5765,Natural ResourcesTransportation and Infrastruc...
881,New York 1st,"Zeldin, Lee",R,2441 RHOB,(202) 225-3826,Financial ServicesForeign Affairs

In [14]:
committee_2022

,District,Name,Party,Office Room,Phone,Committee Assignment
0,1st,"Carl, Jerry L.",R,1330 LHOB,(202) 225-4931,Armed ServicesNatural Resources
1,2nd,"Moore, Barry",R,1504 LHOB,(202) 225-2901,AgricultureVeterans' Affairs
2,3rd,"Rogers, Mike",R,2469 RHOB,(202) 225-3261,Armed Services
3,4th,"Aderholt, Robert",R,266 CHOB,(202) 225-4876,Appropriations
4,5th,"Brooks, Mo",R,2185 RHOB,(202) 225-4801,"Armed ServicesScience, Space, and Technology"
...,...,...,...,...,...,...
877,Virginia 1st,"Wittman, Robert J.",R,2055 RHOB,(202) 225-4261,Armed ServicesNatural Resources
878,Arkansas 3rd,"Womack, Steve",R,2412 RHOB,(202) 225-4301,Appropriations
879,Kentucky 3rd,"Yarmuth, John A.",D,402 CHOB,(202) 225-5401,Budget
880,Alaska At Large,"Young, Don - Vacancy",NaN,2314 RHOB,(202) 225-5765,NaN
881,New York 1st,"Zeldin, Lee",R,2441 RHOB,(202) 225-3826,Financial ServicesForeign Affairs

In [15]:
# Write the DataFrames to separate CSV files
dataframes = [committee_2020, committee_2021, committee_2022]

for i, df in enumerate(dataframes):
    df.to_csv(f"data/RAW-committee_202{i}.csv", sep=',', encoding='utf-8', index=False)